psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'New Zealand' and f.country = 'New Zealand' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Australia' and f.country = 'Australia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uruguay' and f.country = 'Uruguay' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Argentina' and f.country = 'Argentina' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Chile' and f.country = 'Chile' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lesotho' and f.country = 'Lesotho' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Swaziland' and f.country = 'Swaziland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mozambique' and f.country = 'Mozambique' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'South Africa' and f.country = 'South Africa' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Paraguay' and f.country = 'Paraguay' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Botswana' and f.country = 'Botswana' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Namibia' and f.country = 'Namibia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tonga' and f.country = 'Tonga' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mauritius' and f.country = 'Mauritius' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Madagascar' and f.country = 'Madagascar' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Fiji' and f.country = 'Fiji' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Zimbabwe' and f.country = 'Zimbabwe' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Vanuatu' and f.country = 'Vanuatu' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bolivia' and f.country = 'Bolivia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Brazil' and f.country = 'Brazil' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Zambia' and f.country = 'Zambia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malawi' and f.country = 'Malawi' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Samoa' and f.country = 'Samoa' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Peru' and f.country = 'Peru' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Comoros' and f.country = 'Comoros' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Papua New Guinea' and f.country = 'Papua New Guinea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Solomon Islands' and f.country = 'Solomon Islands' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Angola' and f.country = 'Angola' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'East Timor' and f.country = 'East Timor' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tuvalu' and f.country = 'Tuvalu' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Indonesia' and f.country = 'Indonesia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tanzania' and f.country = 'Tanzania' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Seychelles' and f.country = 'Seychelles' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Democratic Republic of the Congo' and f.country = 'Democratic Republic of the Congo' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Republic of Congo' and f.country = 'Republic of Congo' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Burundi' and f.country = 'Burundi' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Rwanda' and f.country = 'Rwanda' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kenya' and f.country = 'Kenya' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nauru' and f.country = 'Nauru' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ecuador' and f.country = 'Ecuador' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uganda' and f.country = 'Uganda' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sao Tome and Principe' and f.country = 'Sao Tome and Principe' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Gabon' and f.country = 'Gabon' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Singapore' and f.country = 'Singapore' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kiribati' and f.country = 'Kiribati' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Somalia' and f.country = 'Somalia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malaysia' and f.country = 'Malaysia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Equatorial Guinea' and f.country = 'Equatorial Guinea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cameroon' and f.country = 'Cameroon' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Maldives' and f.country = 'Maldives' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Central African' and f.country = 'Central African' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Colombia' and f.country = 'Colombia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Brunei' and f.country = 'Brunei' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ghana' and f.country = 'Ghana' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Suriname' and f.country = 'Suriname' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Togo' and f.country = 'Togo' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Liberia' and f.country = 'Liberia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Benin' and f.country = 'Benin' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guyana' and f.country = 'Guyana' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ivory Coast' and f.country = 'Ivory Coast' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sri Lanka' and f.country = 'Sri Lanka' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Micronesia' and f.country = 'Micronesia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Marshall Islands' and f.country = 'Marshall Islands' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Palau' and f.country = 'Palau' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sierra Leone' and f.country = 'Sierra Leone' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Panama' and f.country = 'Panama' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ethiopia' and f.country = 'Ethiopia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nigeria' and f.country = 'Nigeria' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guinea' and f.country = 'Guinea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Costa Rica' and f.country = 'Costa Rica' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Venezuela' and f.country = 'Venezuela' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Trinidad and Tobago' and f.country = 'Trinidad and Tobago' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cambodia' and f.country = 'Cambodia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Djibouti' and f.country = 'Djibouti' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guinea Bissau' and f.country = 'Guinea Bissau' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Grenada' and f.country = 'Grenada' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Chad' and f.country = 'Chad' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nicaragua' and f.country = 'Nicaragua' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Burkina Faso' and f.country = 'Burkina Faso' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mali' and f.country = 'Mali' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Barbados' and f.country = 'Barbados' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Vincent' and f.country = 'Saint Vincent' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Gambia' and f.country = 'Gambia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Niger' and f.country = 'Niger' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'El Salvador' and f.country = 'El Salvador' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Thailand' and f.country = 'Thailand' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Lucia' and f.country = 'Saint Lucia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Honduras' and f.country = 'Honduras' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Philippines' and f.country = 'Philippines' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guatemala' and f.country = 'Guatemala' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Senegal' and f.country = 'Senegal' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cabo Verde' and f.country = 'Cabo Verde' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Dominica' and f.country = 'Dominica' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Eritrea' and f.country = 'Eritrea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Yemen' and f.country = 'Yemen' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sudan' and f.country = 'Sudan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Antigua and Barbuda' and f.country = 'Antigua and Barbuda' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belize' and f.country = 'Belize' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Christopher and Nevis' and f.country = 'Saint Christopher and Nevis' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Laos' and f.country = 'Laos' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Jamaica' and f.country = 'Jamaica' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mauritania' and f.country = 'Mauritania' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Dominican Republic' and f.country = 'Dominican Republic' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Haiti' and f.country = 'Haiti' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mexico' and f.country = 'Mexico' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Myanmar' and f.country = 'Myanmar' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Viet Nam' and f.country = 'Viet Nam' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Hong Kong' and f.country = 'Hong Kong' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cuba' and f.country = 'Cuba' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Oman' and f.country = 'Oman' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bangladesh' and f.country = 'Bangladesh' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Arab' and f.country = 'Arab' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saudi Arabia' and f.country = 'Saudi Arabia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bahamas' and f.country = 'Bahamas' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Taiwan' and f.country = 'Taiwan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Qatar' and f.country = 'Qatar' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bahrain' and f.country = 'Bahrain' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bhutan' and f.country = 'Bhutan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nepal' and f.country = 'Nepal' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'India' and f.country = 'India' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kuwait' and f.country = 'Kuwait' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Egypt' and f.country = 'Egypt' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Israel' and f.country = 'Israel' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Jordan' and f.country = 'Jordan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Libya' and f.country = 'Libya' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iraq' and f.country = 'Iraq' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Syria' and f.country = 'Syria' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Pakistan' and f.country = 'Pakistan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lebanon' and f.country = 'Lebanon' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Morocco' and f.country = 'Morocco' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Afghanistan' and f.country = 'Afghanistan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cyprus' and f.country = 'Cyprus' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iran' and f.country = 'Iran' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malta' and f.country = 'Malta' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Algeria' and f.country = 'Algeria' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tunisia' and f.country = 'Tunisia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'South Korea' and f.country = 'South Korea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Turkmenistan' and f.country = 'Turkmenistan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Greece' and f.country = 'Greece' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tajikistan' and f.country = 'Tajikistan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Portugal' and f.country = 'Portugal' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'United States' and f.country = 'United States' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'North Korea' and f.country = 'North Korea' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'China' and f.country = 'China' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Turkey' and f.country = 'Turkey' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Armenia' and f.country = 'Armenia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Spain' and f.country = 'Spain' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Azerbaijan' and f.country = 'Azerbaijan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uzbekistan' and f.country = 'Uzbekistan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Albania' and f.country = 'Albania' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Georgia' and f.country = 'Georgia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Italy' and f.country = 'Italy' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Vatican City' and f.country = 'Vatican City' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Macedonia' and f.country = 'Macedonia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Andorra' and f.country = 'Andorra' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bulgaria' and f.country = 'Bulgaria' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kyrgyzstan' and f.country = 'Kyrgyzstan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Monaco' and f.country = 'Monaco' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bosnia and Herzegovina' and f.country = 'Bosnia and Herzegovina' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'San Marino' and f.country = 'San Marino' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Romania' and f.country = 'Romania' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Serbia and Montenegro' and f.country = 'Serbia and Montenegro' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Canada' and f.country = 'Canada' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Croatia' and f.country = 'Croatia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Slovenia' and f.country = 'Slovenia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Switzerland' and f.country = 'Switzerland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Moldova' and f.country = 'Moldova' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Liechtenstein' and f.country = 'Liechtenstein' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Hungary' and f.country = 'Hungary' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mongolia' and f.country = 'Mongolia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Slovakia' and f.country = 'Slovakia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Austria' and f.country = 'Austria' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'France' and f.country = 'France' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Luxembourg' and f.country = 'Luxembourg' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Czech Republic' and f.country = 'Czech Republic' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ukraine' and f.country = 'Ukraine' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belgium' and f.country = 'Belgium' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kazakhstan' and f.country = 'Kazakhstan' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'United Kingdom' and f.country = 'United Kingdom' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Poland' and f.country = 'Poland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Netherlands' and f.country = 'Netherlands' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Germany' and f.country = 'Germany' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ireland' and f.country = 'Ireland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belarus' and f.country = 'Belarus' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lithuania' and f.country = 'Lithuania' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Denmark' and f.country = 'Denmark' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Russia' and f.country = 'Russia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Latvia' and f.country = 'Latvia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sweden' and f.country = 'Sweden' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Estonia' and f.country = 'Estonia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Norway' and f.country = 'Norway' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Finland' and f.country = 'Finland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iceland' and f.country = 'Iceland' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Czech Slovakia' and f.country = 'Czech Slovakia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Yugoslavia' and f.country = 'Yugoslavia' and f.year=2005 group by f.country;" >> /mnt/nfs/result.csv
