psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'New Zealand' and f.country = 'New Zealand' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Australia' and f.country = 'Australia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uruguay' and f.country = 'Uruguay' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Argentina' and f.country = 'Argentina' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Chile' and f.country = 'Chile' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lesotho' and f.country = 'Lesotho' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Swaziland' and f.country = 'Swaziland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mozambique' and f.country = 'Mozambique' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'South Africa' and f.country = 'South Africa' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Paraguay' and f.country = 'Paraguay' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Botswana' and f.country = 'Botswana' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Namibia' and f.country = 'Namibia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tonga' and f.country = 'Tonga' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mauritius' and f.country = 'Mauritius' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Madagascar' and f.country = 'Madagascar' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Fiji' and f.country = 'Fiji' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Zimbabwe' and f.country = 'Zimbabwe' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Vanuatu' and f.country = 'Vanuatu' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bolivia' and f.country = 'Bolivia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Brazil' and f.country = 'Brazil' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Zambia' and f.country = 'Zambia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malawi' and f.country = 'Malawi' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Samoa' and f.country = 'Samoa' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Peru' and f.country = 'Peru' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Comoros' and f.country = 'Comoros' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Papua New Guinea' and f.country = 'Papua New Guinea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Solomon Islands' and f.country = 'Solomon Islands' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Angola' and f.country = 'Angola' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'East Timor' and f.country = 'East Timor' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tuvalu' and f.country = 'Tuvalu' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Indonesia' and f.country = 'Indonesia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tanzania' and f.country = 'Tanzania' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Seychelles' and f.country = 'Seychelles' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Democratic Republic of the Congo' and f.country = 'Democratic Republic of the Congo' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Republic of Congo' and f.country = 'Republic of Congo' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Burundi' and f.country = 'Burundi' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Rwanda' and f.country = 'Rwanda' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kenya' and f.country = 'Kenya' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nauru' and f.country = 'Nauru' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ecuador' and f.country = 'Ecuador' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uganda' and f.country = 'Uganda' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sao Tome and Principe' and f.country = 'Sao Tome and Principe' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Gabon' and f.country = 'Gabon' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Singapore' and f.country = 'Singapore' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kiribati' and f.country = 'Kiribati' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Somalia' and f.country = 'Somalia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malaysia' and f.country = 'Malaysia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Equatorial Guinea' and f.country = 'Equatorial Guinea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cameroon' and f.country = 'Cameroon' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Maldives' and f.country = 'Maldives' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Central African' and f.country = 'Central African' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Colombia' and f.country = 'Colombia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Brunei' and f.country = 'Brunei' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ghana' and f.country = 'Ghana' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Suriname' and f.country = 'Suriname' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Togo' and f.country = 'Togo' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Liberia' and f.country = 'Liberia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Benin' and f.country = 'Benin' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guyana' and f.country = 'Guyana' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ivory Coast' and f.country = 'Ivory Coast' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sri Lanka' and f.country = 'Sri Lanka' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Micronesia' and f.country = 'Micronesia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Marshall Islands' and f.country = 'Marshall Islands' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Palau' and f.country = 'Palau' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sierra Leone' and f.country = 'Sierra Leone' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Panama' and f.country = 'Panama' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ethiopia' and f.country = 'Ethiopia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nigeria' and f.country = 'Nigeria' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guinea' and f.country = 'Guinea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Costa Rica' and f.country = 'Costa Rica' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Venezuela' and f.country = 'Venezuela' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Trinidad and Tobago' and f.country = 'Trinidad and Tobago' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cambodia' and f.country = 'Cambodia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Djibouti' and f.country = 'Djibouti' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guinea Bissau' and f.country = 'Guinea Bissau' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Grenada' and f.country = 'Grenada' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Chad' and f.country = 'Chad' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nicaragua' and f.country = 'Nicaragua' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Burkina Faso' and f.country = 'Burkina Faso' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mali' and f.country = 'Mali' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Barbados' and f.country = 'Barbados' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Vincent' and f.country = 'Saint Vincent' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Gambia' and f.country = 'Gambia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Niger' and f.country = 'Niger' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'El Salvador' and f.country = 'El Salvador' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Thailand' and f.country = 'Thailand' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Lucia' and f.country = 'Saint Lucia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Honduras' and f.country = 'Honduras' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Philippines' and f.country = 'Philippines' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Guatemala' and f.country = 'Guatemala' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Senegal' and f.country = 'Senegal' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cabo Verde' and f.country = 'Cabo Verde' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Dominica' and f.country = 'Dominica' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Eritrea' and f.country = 'Eritrea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Yemen' and f.country = 'Yemen' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sudan' and f.country = 'Sudan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Antigua and Barbuda' and f.country = 'Antigua and Barbuda' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belize' and f.country = 'Belize' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saint Christopher and Nevis' and f.country = 'Saint Christopher and Nevis' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Laos' and f.country = 'Laos' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Jamaica' and f.country = 'Jamaica' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mauritania' and f.country = 'Mauritania' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Dominican Republic' and f.country = 'Dominican Republic' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Haiti' and f.country = 'Haiti' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mexico' and f.country = 'Mexico' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Myanmar' and f.country = 'Myanmar' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Viet Nam' and f.country = 'Viet Nam' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Hong Kong' and f.country = 'Hong Kong' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cuba' and f.country = 'Cuba' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Oman' and f.country = 'Oman' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bangladesh' and f.country = 'Bangladesh' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Arab' and f.country = 'Arab' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Saudi Arabia' and f.country = 'Saudi Arabia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bahamas' and f.country = 'Bahamas' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Taiwan' and f.country = 'Taiwan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Qatar' and f.country = 'Qatar' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bahrain' and f.country = 'Bahrain' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bhutan' and f.country = 'Bhutan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Nepal' and f.country = 'Nepal' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'India' and f.country = 'India' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kuwait' and f.country = 'Kuwait' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Egypt' and f.country = 'Egypt' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Israel' and f.country = 'Israel' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Jordan' and f.country = 'Jordan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Libya' and f.country = 'Libya' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iraq' and f.country = 'Iraq' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Syria' and f.country = 'Syria' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Pakistan' and f.country = 'Pakistan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lebanon' and f.country = 'Lebanon' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Morocco' and f.country = 'Morocco' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Afghanistan' and f.country = 'Afghanistan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Cyprus' and f.country = 'Cyprus' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iran' and f.country = 'Iran' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Malta' and f.country = 'Malta' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Algeria' and f.country = 'Algeria' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tunisia' and f.country = 'Tunisia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'South Korea' and f.country = 'South Korea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Turkmenistan' and f.country = 'Turkmenistan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Greece' and f.country = 'Greece' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Tajikistan' and f.country = 'Tajikistan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Portugal' and f.country = 'Portugal' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'United States' and f.country = 'United States' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'North Korea' and f.country = 'North Korea' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'China' and f.country = 'China' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Turkey' and f.country = 'Turkey' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Armenia' and f.country = 'Armenia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Spain' and f.country = 'Spain' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Azerbaijan' and f.country = 'Azerbaijan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Uzbekistan' and f.country = 'Uzbekistan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Albania' and f.country = 'Albania' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Georgia' and f.country = 'Georgia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Italy' and f.country = 'Italy' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Vatican City' and f.country = 'Vatican City' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Macedonia' and f.country = 'Macedonia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Andorra' and f.country = 'Andorra' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bulgaria' and f.country = 'Bulgaria' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kyrgyzstan' and f.country = 'Kyrgyzstan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Monaco' and f.country = 'Monaco' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Bosnia and Herzegovina' and f.country = 'Bosnia and Herzegovina' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'San Marino' and f.country = 'San Marino' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Romania' and f.country = 'Romania' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Serbia and Montenegro' and f.country = 'Serbia and Montenegro' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Canada' and f.country = 'Canada' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Croatia' and f.country = 'Croatia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Slovenia' and f.country = 'Slovenia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Switzerland' and f.country = 'Switzerland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Moldova' and f.country = 'Moldova' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Liechtenstein' and f.country = 'Liechtenstein' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Hungary' and f.country = 'Hungary' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Mongolia' and f.country = 'Mongolia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Slovakia' and f.country = 'Slovakia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Austria' and f.country = 'Austria' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'France' and f.country = 'France' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Luxembourg' and f.country = 'Luxembourg' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Czech Republic' and f.country = 'Czech Republic' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ukraine' and f.country = 'Ukraine' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belgium' and f.country = 'Belgium' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Kazakhstan' and f.country = 'Kazakhstan' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'United Kingdom' and f.country = 'United Kingdom' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Poland' and f.country = 'Poland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Netherlands' and f.country = 'Netherlands' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Germany' and f.country = 'Germany' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Ireland' and f.country = 'Ireland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Belarus' and f.country = 'Belarus' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Lithuania' and f.country = 'Lithuania' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Denmark' and f.country = 'Denmark' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Russia' and f.country = 'Russia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Latvia' and f.country = 'Latvia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Sweden' and f.country = 'Sweden' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Estonia' and f.country = 'Estonia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Norway' and f.country = 'Norway' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Finland' and f.country = 'Finland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Iceland' and f.country = 'Iceland' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Czech Slovakia' and f.country = 'Czech Slovakia' group by f.country;" >> /mnt/nfs/result.csv
psql pgdemo -t -AF "," -c "select avg(f.year)::int, f.country, avg(i.lat), avg(i.lon), count(*),to_char(CURRENT_TIMESTAMP,'YYYY-MM-DD\"T\"HH24:MI:SS+0900') from ido i, foreigner_europe f where i.country = 'Yugoslavia' and f.country = 'Yugoslavia' group by f.country;" >> /mnt/nfs/result.csv
